name: Build ZeroHedge FAISS Vectorstore

on:
  push:
    branches:
      - zzLotteryTicket

jobs:
  build-faiss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ZeroHedge FAISS image
        uses: docker/build-push-action@v5
        with:
          context: ./commands/vectorstore_cmd
          file: ./commands/vectorstore_cmd/Dockerfile
          push: true
          tags: alienzimzum/zerohedge_faiss:latest
