# .github/workflows/vectorstore_zerohedge_faiss.yml
name: Build ZeroHedge FAISS Vectorstore

on:
  workflow_dispatch:

jobs:
  build-faiss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push zerohedge_faiss
        uses: docker/build-push-action@v5
        with:
          context: .
          file: commands/vectorstore_cmd/Dockerfile
          push: true
          tags: alienzimzum/zerohedge_faiss:latest
